baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Netlify + Hugo Quickstart'
theme = 'lynx' 

[module]
  [[module.imports]]
	path = "github.com/jpanther/lynx"
	# project theme

